-- ============================================================
-- KRAKEN V15
-- MAILING LIST
-- ============================================================

CREATE TABLE IF NOT EXISTS public.mailing_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  subscribed BOOLEAN NOT NULL DEFAULT TRUE,
  source TEXT NOT NULL DEFAULT 'homepage',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.mailing_list ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can join mailing list"
ON public.mailing_list;

CREATE POLICY "Anyone can join mailing list"
ON public.mailing_list
FOR INSERT
TO anon, authenticated
WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Anyone can resubscribe mailing list"
ON public.mailing_list;

CREATE POLICY "Anyone can resubscribe mailing list"
ON public.mailing_list
FOR UPDATE
TO anon, authenticated
USING (TRUE)
WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Admins read mailing list"
ON public.mailing_list;

CREATE POLICY "Admins read mailing list"
ON public.mailing_list
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE admin_users.user_id = auth.uid()
  )
);

NOTIFY pgrst, 'reload schema';
